name: "HCL AppScan SAST - 360"
on:
  workflow_dispatch
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run AppScan SAST scan
        uses: HCL-TECH-SOFTWARE/appscan-sast-action@UpdateExtractZip
        with:
          asoc_key: ${{secrets.ASOC_KEY}}
          asoc_secret: ${{secrets.ASOC_SECRET}}
          application_id: 36bf69fa-8a49-4b46-bf40-86a72ebdefe0
          service_url: https://ascp-02-as360-sast-dev.eastus.cloudapp.azure.com
          acceptssl: true
